const SUPABASE_URL = "https://vbrezgsxbfxtfzfcmqce.supabase.co";
const SUPABASE_KEY = "sb_publishable_mwJdpfrhPEZCxzHIrJ-7_w_jze0OPzT";
const db = window.supabase?.createClient(SUPABASE_URL, SUPABASE_KEY);
const ID_KEY = "universo-experiencia.identidad.v2";
const SESSION_KEY = "universo-experiencia.sesion.v3";
const steps = [["lanzamiento", "Centro de lanzamiento", "Puerta de entrada al cúmulo Grupo EPM"], ["estrellas", "Estrellas cliente", "Clientes y usuarios orbitan el centro de su galaxia"], ["planetas", "Planetas de talento", "Empleados, roles y competencias alrededor del cliente"], ["coordenadas", "Constelación guía", "Modelo de experiencia y arquitectura empresarial"], ["satelites", "Satélites del ecosistema", "Proveedores y contratistas, Dueño y Comunidad"], ["observatorio", "Observatorio de señales", "Medir para aprender y actuar"], ["mision", "Misión en la Tierra", "Convertir aprendizaje en acción"]];
const planets = { empaticos:{name:"Planeta de los Empáticos",power:"Lees necesidades y emociones antes de buscar una respuesta.",color:"#3fd6a8"}, conectores:{name:"Planeta de los Conectores",power:"Conectas perspectivas y haces que las personas trabajen juntas.",color:"#6fb6ff"}, impulsores:{name:"Planeta de los Impulsores",power:"Das dirección a la energía del equipo para que las promesas se cumplan.",color:"#ffc15e"}, exploradores:{name:"Planeta de los Exploradores",power:"Encuentras caminos posibles cuando el contexto cambia.",color:"#c77bff"}, forjadores:{name:"Planeta de los Forjadores",power:"Conviertes la experiencia diaria en crecimiento personal y ejemplo.",color:"#b7e05a"} };
const duels = [
  ["Cambian un procedimiento justo cuando ya tenías todo organizado.",["exploradores","Reorganizo rápido la ruta y pruebo cómo hacerlo funcionar."],["impulsores","Primero aclaro cuál es el resultado que no podemos perder de vista."]],
  ["Una persona llega con una solicitud bastante confusa.",["empaticos","Le hago preguntas y escucho hasta comprender qué necesita."],["conectores","Identifico quién puede ayudar y conecto a las personas necesarias."]],
  ["Terminas algo importante para un cliente o usuario.",["forjadores","Reviso qué aprendí y qué haría diferente la próxima vez."],["impulsores","Me aseguro de que todo haya quedado cerrado y el resultado se haya cumplido."]],
  ["Aparece una fricción repetida en el recorrido.",["exploradores","Propongo una prueba pequeña para encontrar una nueva forma de resolverla."],["empaticos","Busco escuchar cómo está viviendo la fricción la persona."]],
  ["Dos equipos tienen miradas distintas sobre una misma situación.",["conectores","Creo una conversación para construir una respuesta conjunta."],["forjadores","Observo mi postura y pregunto qué puedo ajustar para colaborar mejor."]],
  ["Una promesa hecha a un cliente está en riesgo.",["impulsores","Defino responsables y un siguiente paso claro para cumplirla."],["empaticos","Me comunico con honestidad para entender y cuidar lo que siente la persona."]],
  ["Tu equipo recibe una nueva señal del entorno.",["exploradores","Exploro cómo puede cambiar nuestra ruta y qué oportunidad aparece."],["conectores","Comparto la señal con quienes pueden convertirla en una respuesta útil."]],
  ["Recibes una retroalimentación inesperada.",["forjadores","La tomo como una oportunidad para observarme y crecer."],["exploradores","La uso para probar una manera distinta de hacer las cosas."]],
  ["El cliente debe pasar por varios momentos para resolver algo.",["conectores","Vinculo a las áreas para que el recorrido se sienta como uno solo."],["impulsores","Hago visible el resultado esperado y el compromiso de cada momento."]],
  ["Algo no salió como esperabas.",["forjadores","Me pregunto qué puedo aprender antes de seguir."],["empaticos","Busco comprender el impacto que tuvo en las personas."]]
];
let clientId = localStorage.getItem(ID_KEY); if (!clientId) { clientId = crypto.randomUUID(); localStorage.setItem(ID_KEY, clientId); }
let sessionToken = localStorage.getItem(SESSION_KEY) || "";
let participantEmail = "";
let feedback = {rating:0,recommendation:""};
let heartbeatTimer;
let trip = {name:"",step:"lanzamiento",duels:{},satellites:[],mission:{}}; let view = "start"; let duelIndex = 0; let localAnswer = ""; let pendingSatellites = [];
const app = document.querySelector("#app");
const safe = (v) => String(v || "").replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function feedbackDialog() { return `<dialog class="feedback-dialog" id="feedback-dialog" aria-labelledby="feedback-title"><form method="dialog" class="feedback-card" onsubmit="saveFeedback(event)"><button class="dialog-close" type="button" onclick="closeFeedback()" aria-label="Cerrar">×</button><p class="tag">Tu voz orienta el viaje</p><h2 id="feedback-title">Evalúa la experiencia</h2><p>Cuéntanos cómo viviste este universo y qué podríamos mejorar.</p><fieldset><legend>¿Cómo calificas la experiencia?</legend><div class="rating-stars">${[1,2,3,4,5].map((n)=>`<label><input type="radio" name="rating" value="${n}" ${feedback.rating===n?"checked":""} required><span aria-hidden="true">★</span><small>${n}</small></label>`).join("")}</div></fieldset><label class="feedback-copy">Recomendaciones<textarea id="feedback-recommendation" maxlength="2000" placeholder="Déjanos una recomendación concreta…">${safe(feedback.recommendation)}</textarea></label><p class="feedback-status" id="feedback-status" role="status"></p><div class="dialog-actions"><button class="secondary" type="button" onclick="closeFeedback()">Cancelar</button><button class="primary" type="submit">Enviar evaluación</button></div></form></dialog>`; }
function nav() { const signed=Boolean(sessionToken); return `<nav class="site-nav"><button class="nav-epm" onclick="${signed?'showMap()':'render()'}" aria-label="${signed?'Ir al universo':'Grupo EPM'}"><img class="epm-logo" src="assets/logo-grupo-epm.png" alt="Grupo EPM"></button><button class="nav-button nav-product" onclick="${signed?'showMap()':'render()'}"><span>Universo de la Experiencia</span><i aria-hidden="true">—</i><strong>Guía de la Experiencia</strong></button><div class="nav-actions">${signed?`<button class="nav-button nav-passport" ${trip.mainPlanet?"":"disabled"} onclick="showPassport()"><span>Mi pasaporte</span><b aria-hidden="true">▣</b></button><button class="nav-button nav-feedback" onclick="openFeedback()"><span>Evaluar experiencia</span><b aria-hidden="true">★</b></button><button class="nav-button nav-logout" onclick="logoutParticipant()" aria-label="Cerrar sesión" title="Cerrar sesión">↗</button>`:""}</div></nav>${signed?feedbackDialog():""}`; }
function error(message) { return message ? `<p class="error">${safe(message)}</p>` : ""; }
function rpcPayload(data) { return Array.isArray(data) ? data[0] : data; }
function normalizeSatelliteId(value) {
  const id=String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
  if(["proveedores","proveedor","contratistas","proveedores y contratistas"].includes(id))return "proveedores";
  if(["dueno","dueno de experiencia"].includes(id))return "dueno";
  if(id==="comunidad")return "comunidad";
  return "";
}
function normalizeSatellites(value) {
  let source=value;
  if(typeof source==="string"){
    try{const parsed=JSON.parse(source);source=Array.isArray(parsed)?parsed:[source];}catch{source=[source];}
  }
  if(!Array.isArray(source))return [];
  return [...new Set(source.map(normalizeSatelliteId).filter(Boolean))].slice(0,3);
}
function hydrate(payload) {
  const result=rpcPayload(payload)||{},row=result.viaje||result;
  participantEmail=result.correo||participantEmail;
  trip={name:row.nombre||trip.name||"",step:row.paso||"lanzamiento",duels:row.duelos||{},mainPlanet:row.planeta_principal||undefined,explorePlanet:row.planeta_explorar||undefined,role:row.rol||undefined,satellites:normalizeSatellites(row.satelites),observatory:row.observatorio||undefined,mission:row.mision||{}};
  const saved=result.feedback||null;feedback=saved?{rating:Number(saved.calificacion)||0,recommendation:saved.recomendacion||""}:{rating:0,recommendation:""};
  pendingSatellites=[...trip.satellites];
}
function tripPayload(changes) {
  const payload={},has=(key)=>Object.prototype.hasOwnProperty.call(changes,key);
  if(has("name"))payload.nombre=String(changes.name||"").trim();
  if(has("step"))payload.paso=changes.step;
  if(has("duels"))payload.duelos=changes.duels||{};
  if(has("mainPlanet"))payload.planeta_principal=changes.mainPlanet||null;
  if(has("explorePlanet"))payload.planeta_explorar=changes.explorePlanet||null;
  if(has("role"))payload.rol=changes.role||null;
  if(has("satellites"))payload.satelites=normalizeSatellites(changes.satellites);
  if(has("observatory"))payload.observatorio=changes.observatory||null;
  if(has("mission"))payload.mision=changes.mission||{};
  return payload;
}
function startHeartbeat() { clearInterval(heartbeatTimer); if(!sessionToken)return; heartbeatTimer=setInterval(()=>db?.rpc("universo_heartbeat",{p_token:sessionToken}),45000); }
function sessionError(err) { return /token|sesión|sesion|expir/i.test(err?.message||""); }
async function load() {
  if(!db)return render("No se pudo iniciar la conexión con Supabase.");
  if(!sessionToken)return render();
  try{
    const {data,error:err}=await db.rpc("universo_mi_viaje",{p_token:sessionToken});
    if(err)throw err;hydrate(data);view="map";startHeartbeat();render();
  }catch(err){localStorage.removeItem(SESSION_KEY);sessionToken="";view="start";render(sessionError(err)?"Tu sesión terminó. Ingresa nuevamente con tu correo.":`No pudimos recuperar tu viaje: ${err.message||"revisa la conexión con Supabase."}`);}
}
async function persist(changes, nextView) {
  const next={...trip,...changes};
  if(!sessionToken){view="start";render("Ingresa con tu correo para guardar el viaje.");return false;}
  if(!next.name||next.name.trim().length<2){render("Escribe tu nombre completo para continuar.");return false;}
  try{
    const {data,error:err}=await db.rpc("universo_guardar_viaje",{p_token:sessionToken,p_viaje:tripPayload(changes)});
    if(err)throw err;trip=next;if(data)hydrate(data);if(nextView)view=nextView;startHeartbeat();render();return true;
  }catch(err){if(sessionError(err)){localStorage.removeItem(SESSION_KEY);sessionToken="";view="start";}render(`No pudimos guardar tu avance: ${err.message||"intenta de nuevo."}`);return false;}
}
function render(message="") { window.destroyClientOrbitalScene?.(); if(view==="start") return renderStart(message); if(view==="map"){renderClientCenteredRealm(message); window.requestAnimationFrame(()=>window.initClientOrbitalScene?.(steps.findIndex((s)=>s[0]===trip.step))); return;} if(view==="passport") return renderPassport(); renderJourney(message); }
function renderOrbitalRealm(message) { const index=steps.findIndex((s)=>s[0]===trip.step); const objects=[['launch','lanzamiento','Centro de lanzamiento','assets/cohete-realista.png','18','-7'],['stars','estrellas','Las estrellas','assets/estrella-realista.png','23','-14'],['planets','planetas','Los planetas','assets/planeta-anillado.png','28','-21'],['coordinates','coordenadas','Coordenadas','assets/coordenadas-3d.png','25','-9'],['satellites','satelites','Satélites y constelaciones','assets/satelites-constelacion.png','31','-17'],['observatory','observatorio','Observatorio de señales','assets/observatorio-orbital.png','34','-27']]; const bodies=objects.map((o,i)=>`<div class="realm-ring realm-ring-${o[0]}" aria-hidden="true"></div><button class="realm-body realm-body-${o[0]} ${i<=index?'available':''}" style="--duration:${o[4]}s;--delay:${o[5]}s" ${i>index?'disabled':''} onclick="goStep('${o[1]}')"><span class="realm-art"><img src="${o[3]}" alt=""></span><span class="realm-label"><small>${i<index?'COMPLETADO':i===index?'SIGUIENTE SEÑAL':`MOMENTO ${i+1}`}</small><b>${o[2]}</b></span></button>`).join(''); const missionIndex=steps.findIndex(s=>s[0]==='mision'); app.innerHTML=`<main class="universo orbital-realm-view">${nav()}<section class="orbital-realm" aria-label="Sistema orbital interactivo"><button class="realm-core ${missionIndex<=index?'available':''}" ${missionIndex>index?'disabled':''} onclick="goStep('mision')"><img src="assets/tierra-realista.png" alt="Misión en la Tierra"><span class="realm-label"><small>${missionIndex<index?'COMPLETADO':missionIndex===index?'SIGUIENTE SEÑAL':'MOMENTO 7'}</small><b>Misión en la Tierra</b></span></button>${bodies}</section>${error(message)}</main>`; }

function renderClientCenteredRealm(message="") {
  const index=steps.findIndex((s)=>s[0]===trip.step);
  app.innerHTML=`<main class="universo orbital-realm-view">${nav()}<section class="orbital-realm" aria-label="Galaxia, estrellas cliente y sistemas de empleados"><div class="cosmos-fallback"><p>Preparando tu universo en 3D…</p><div>${steps.map((s,i)=>`<button ${i>index?'disabled':''} onclick="goStep('${s[0]}')">${s[1]}</button>`).join('')}</div></div></section>${error(message)}</main>`;
}

function renderStart(message) { app.innerHTML=`<main class="universo start-view">${nav()}<section class="hero access-hero"><p class="tag">Bienvenido/a a la Guía de la Experiencia</p><h1>Tu viaje empieza<br><em>en este universo.</em></h1><p class="intro">Ingresa con tu correo para guardar el progreso y recuperarlo cuando regreses.</p><form class="access-form" onsubmit="loginParticipant(event)"><label class="field">Nombre completo<input id="name" value="${safe(trip.name)}" placeholder="Tu nombre y apellidos" autocomplete="name" maxlength="80" required></label><label class="field">Correo electrónico<input id="email" type="email" value="${safe(participantEmail)}" placeholder="nombre@correo.com" autocomplete="email" maxlength="254" required></label><button class="primary" type="submit">Ingresar a mi viaje →</button></form>${error(message)}<small>Si es tu primera vez, crearemos tu registro. Si ya participaste, encontrarás tu avance.</small><a class="admin-entry" href="admin.html">Acceso administrador</a></section></main>`; }
function renderMap(message) { const index=steps.findIndex((s)=>s[0]===trip.step); const celestial={lanzamiento:"rocket",estrellas:"constellation",planetas:"earth",coordenadas:"coordinates",satelites:"satellite",observatorio:"observatory",mision:"terra"}; const locations=[["22%","24%"],["49%","12%"],["76%","25%"],["84%","55%"],["61%","79%"],["31%","76%"],["13%","54%"]]; const visuals=["🚀","✦","🌍","✧","🪐","⌕","🌎"]; const bodies=steps.map((s,i)=>`<button class="visible-celestial ${celestial[s[0]]}" style="position:absolute;left:${locations[i][0]};top:${locations[i][1]};transform:translate(-50%,-50%);z-index:2;width:112px;height:112px;padding:0;border:0;background:transparent;color:#fff;pointer-events:auto;animation:direct-orbit ${8+i}s ease-in-out ${-i}s infinite alternate" ${i>index?"disabled":""} onclick="goStep('${s[0]}')" aria-label="${s[1]}"><span style="display:grid;place-items:center;width:76px;height:76px;margin:auto;border-radius:50%;background:radial-gradient(circle at 30% 24%,#fff 0 3%,#a6ecff 6%,#408dd7 27%,#281268 69%,#07081f 100%);box-shadow:inset -10px -9px 15px #05051f,0 0 24px #58e5ff,0 0 46px #a451ff;font-size:2.25rem">${visuals[i]}</span><span style="display:block;margin-top:4px;text-align:center;text-shadow:0 2px 8px #000"><small style="display:block;color:#d9ff5c;font-size:.5rem;letter-spacing:.1em;font-weight:900">${i<index?"COMPLETADO":i===index?"SIGUIENTE SEÑAL":`MOMENTO ${i+1}`}</small><b style="font-size:.78rem">${s[1]}</b></span></button>`).join(""); app.innerHTML=`<main class="universo map-view">${nav()}<section class="map-head"><div><p class="tag">Universo → mapa de navegación</p><p>Selecciona los objetos celestes para abrir cada territorio de la experiencia.</p></div><div class="counter"><b>${Math.max(0,index+1)}<small>de 7 momentos</small></b><span>Tu viaje</span></div></section><div style="position:fixed;left:0;right:0;top:195px;bottom:0;z-index:30;pointer-events:none;overflow:hidden" aria-label="Mapa orbital de navegación"><div style="position:absolute;left:50%;top:51%;transform:translate(-50%,-50%);width:155px;height:155px;border-radius:50%;background:radial-gradient(circle at 30% 25%,#efffff 0 4%,#85edff 6%,#1689d1 29%,#23ba94 32% 45%,#075a74 48% 67%,#100b50 100%);box-shadow:inset -18px -16px 27px #040624,0 0 30px #44e8ff,0 0 80px #764eff"><b style="position:absolute;top:108%;left:50%;transform:translateX(-50%);white-space:nowrap;color:white;font-size:.85rem">Tu experiencia</b></div>${bodies}</div>${error(message)}</main>`; }
function renderJourney(message) { const index=steps.findIndex((s)=>s[0]===trip.step); let content=""; if(trip.step==="lanzamiento") content=launch(); if(trip.step==="estrellas") content=stars(); if(trip.step==="planetas") content=planetsLesson(); if(trip.step==="coordenadas") content=coordinates(); if(trip.step==="satelites") content=satellites(); if(trip.step==="observatorio") content=observatory(); if(trip.step==="mision") content=mission(); app.innerHTML=`<main class="universo journey-view">${nav()}<div class="progress"><i style="width:${(index+1)/steps.length*100}%"></i></div>${content}${error(message)}</main>`; }
function launch(){return `<article class="lesson"><p class="tag">01 · Centro de lanzamiento</p><h1>Antes de despegar, hablemos el mismo idioma.</h1><p class="intro">La experiencia no es un área ni un momento aislado: es la percepción que una persona construye a lo largo de su relación con nosotros.</p><div class="choices">${[["experience","Experiencia","La percepción completa que queda en una persona."],["service","Servicio","Solo el contacto final con una persona."],["process","Proceso","Una lista de pasos internos sin conexión con el cliente."]].map(x=>`<button class="choice ${localAnswer===x[0]?"selected":""}" onclick="answer('${x[0]}')"><b>${x[1]}</b><small>${x[2]}</small></button>`).join("")}</div>${localAnswer?`<p class="message ${localAnswer==="experience"?"good":""}">${localAnswer==="experience"?"Exacto. La guía nos ayuda a diseñar cada decisión desde la experiencia de clientes y usuarios.":"Un servicio y un proceso influyen, pero la experiencia es la percepción total de quien la vive."}</p>`:""}<button class="primary" ${localAnswer!=="experience"?"disabled":""} onclick="goStep('estrellas')">Ir a las estrellas →</button></article>`;}
function stars(){return `<article class="lesson"><p class="tag">02 · Estrellas cliente</p><h1>Clientes y usuarios orientan el universo.</h1><p class="intro">Cada empresa es una galaxia dentro de un grupo o cúmulo. Las estrellas representan a sus clientes y usuarios y orbitan el centro galáctico. Alrededor de las estrellas viajan los planetas: empleados que ponen sus roles y competencias al servicio de la experiencia.</p><section class="story"><small>SEÑAL RECIBIDA</small><h2>“No sabía qué seguía y tuve que llamar tres veces.”</h2><p>¿Cuál es el primer movimiento que más ayuda a esta persona?</p>${[["listen","Comprender el recorrido y la incertidumbre que está viviendo."],["explain","Explicar solo que el proceso tiene varios pasos."],["close","Cerrar el caso sin revisar si entiende el siguiente paso."]].map(x=>`<button class="${localAnswer===x[0]?"selected":""}" onclick="answer('${x[0]}')">${x[1]}</button>`).join("")}</section>${localAnswer?`<p class="message ${localAnswer==="listen"?"good":""}">${localAnswer==="listen"?"La señal pide comprensión y claridad. Cada decisión comienza por la persona y su contexto.":"Antes de responder, necesitamos comprender lo que la persona está viviendo."}</p>`:""}<button class="primary" ${localAnswer!=="listen"?"disabled":""} onclick="goStep('planetas')">Descubrir mi planeta →</button></article>`;}
function planetsLesson(){const d=duels[duelIndex];return `<article class="lesson"><p class="tag">03 · Planetas de talento · duelo orbital ${duelIndex+1}/10</p><h1>Tu planeta reúne roles y competencias.</h1><p class="intro">Los planetas representan a los empleados y orbitan las estrellas cliente. Tus competencias se expresan en cómo escuchas, conectas, impulsas, exploras y aprendes; tu rol puede ser Generador, Diseñador o Habilitador. Elige la forma de actuar que más se parece a ti.</p><p class="scenario">${d[0]}</p><div class="duel-cards">${orbital(d[1])}<span>o</span>${orbital(d[2])}</div></article>`;}
function orbital(item){return `<button class="orbital" style="--color:${planets[item[0]].color}" onclick="pickDuel('${item[0]}')"><small>${planets[item[0]].name}</small><strong>${item[1]}</strong></button>`;}
function coordinates(){const p=planets[trip.mainPlanet], e=planets[trip.explorePlanet];return `<article class="lesson"><p class="tag">04 · Constelación guía</p><h1>Una guía para orientar tu rol.</h1><section class="result-card" style="--color:${p.color}"><small>LAS COMPETENCIAS DE TU PLANETA</small><h2>${p.name}</h2><p>${p.power}</p><div>También puedes explorar: <b>${e.name}</b></div></section><p class="intro">Las constelaciones son dibujos aparentes entre estrellas, no estructuras físicas. Aquí representan el modelo de experiencia y la arquitectura empresarial: una guía compartida para orientar decisiones. Tu rol pertenece a tu planeta. Elige cómo aportas a la experiencia:</p><div class="choices">${[["generador","Generador","Hace realidad la promesa en la interacción y la operación."],["disenador","Diseñador","Piensa y mejora recorridos, soluciones y decisiones."],["habilitador","Habilitador","Crea condiciones y conexiones para que otros cumplan la promesa."]].map(x=>`<button class="choice" onclick="pickRole('${x[0]}')"><b>${x[1]}</b><small>${x[2]}</small></button>`).join("")}</div></article>`;}
function satellites(){const options=[["proveedores","Proveedores y contratistas","Conectan capacidades y recursos para cumplir la promesa."],["dueno","Dueño","Aporta su perspectiva sobre el propósito y las decisiones de la empresa."],["comunidad","Comunidad","Aporta necesidades, expectativas y conocimiento del territorio."]];return `<article class="lesson"><p class="tag">05 · Satélites del ecosistema</p><h1>Ningún planeta viaja solo.</h1><p class="intro">Los satélites representan a Proveedores y contratistas, Dueño y Comunidad. Orbitan alrededor de los planetas y acompañan a los empleados en su aporte a la experiencia. Elige los actores con quienes necesitas conectar para cumplir tu misión.</p><div class="satellites">${options.map(x=>`<button class="${pendingSatellites.includes(x[0])?"selected":""}" onclick="toggleSatellite('${x[0]}')"><i>◌</i><b>${x[1]}</b><small>${x[2]}</small></button>`).join("")}</div><button class="primary" ${pendingSatellites.length?"":"disabled"} onclick="saveSatellites()">Ir al observatorio →</button></article>`;}
function observatory(){return `<article class="lesson"><p class="tag">06 · Observatorio de señales</p><h1>Medir sirve para aprender y decidir.</h1><p class="intro">Cada indicador revela una señal distinta. No se trata de mirar números aislados, sino de hacer preguntas que nos permitan mejorar.</p><section class="story"><small>CASO DEL OBSERVATORIO</small><h2>Quieres saber cuánto esfuerzo tuvo que hacer una persona para resolver su necesidad.</h2>${[["nps","NPS · Recomendación y lealtad"],["is","IS · Satisfacción con una interacción"],["ces","CES · Esfuerzo del cliente"],["enps","eNPS / IEX · Experiencia de colaboradores"]].map(x=>`<button class="${localAnswer===x[0]?"selected":""}" onclick="answer('${x[0]}')">${x[1]}</button>`).join("")}</section>${localAnswer?`<p class="message ${localAnswer==="ces"?"good":""}">${localAnswer==="ces"?"Correcto. El CES permite entender y reducir el esfuerzo que una persona debe hacer en su recorrido.":"Ese instrumento observa otra señal. Vuelve al propósito de comprender el esfuerzo de la persona."}</p>`:""}<button class="primary" ${localAnswer!=="ces"?"disabled":""} onclick="saveObservatory()">Definir mi misión →</button></article>`;}
function mission(){const m=trip.mission||{};return `<article class="lesson"><p class="tag">07 · Misión en la Tierra</p><h1>El viaje termina en acción.</h1><p class="intro">Tu misión sigue el modelo 70/20/10: aprender haciendo, con otros y mediante formación.</p><div class="mission-grid"><label><b>70% · Una acción que voy a probar</b><textarea id="action" placeholder="Ej.: Simplificaré el siguiente paso del proceso para una persona.">${safe(m.accion)}</textarea></label><label><b>20% · Con quién voy a aprender</b><select id="with"><option value="">Elige una opción</option>${["Líder","Compañero/a","Comunidad de práctica","Referente de otra área"].map(x=>`<option ${m.conQuien===x?"selected":""}>${x}</option>`).join("")}</select></label><label><b>10% · Algo que quiero aprender</b><select id="learning"><option value="">Elige una opción</option>${["Escucha y comprensión de necesidades","Diseño de recorridos y momentos","Trabajo colaborativo","Medición y aprendizaje continuo"].map(x=>`<option ${m.aprendizaje===x?"selected":""}>${x}</option>`).join("")}</select></label></div><button class="primary" onclick="saveMission()">Generar mi pasaporte espacial ✦</button></article>`;}
function renderPassport(){if(!trip.mainPlanet){view="map";return renderMap();}const p=planets[trip.mainPlanet],m=trip.mission||{};app.innerHTML=`<main class="universo">${nav()}<section class="passport" id="passport-card"><img class="passport-logo" src="assets/logo-grupo-epm.png" alt="Grupo EPM"><div class="seal">✦ PASAPORTE ESPACIAL</div><p>EXPLORADOR/A</p><h1>${safe(trip.name)}</h1><section class="passport-data"><div><small>MIS COORDENADAS</small><b>${safe(trip.role||"Por definir")}</b></div><div><small>MI PLANETA PRINCIPAL</small><b style="color:${p.color}">${p.name.replace("Planeta de los ","")}</b></div><div><small>MI SUPERPODER</small><b>${p.power}</b></div><div><small>MI PRÓXIMA MISIÓN</small><b>${safe(m.accion||"Por definir")}</b></div><div><small>APRENDERÉ CON</small><b>${safe(m.conQuien||"Por definir")}</b></div><div><small>QUIERO APRENDER</small><b>${safe(m.aprendizaje||"Por definir")}</b></div></section><footer>Tu aporte ya hace parte del Universo de la Experiencia.</footer></section><div class="passport-actions"><button class="secondary" onclick="showMap()">← Volver al mapa</button><button class="primary" onclick="downloadPassport()">Descargar mi pasaporte PDF</button></div></main>`;}
async function downloadPassport(){const card=document.querySelector('#passport-card');if(!card||!window.html2canvas||!window.jspdf){return window.print();}const button=document.querySelector('.passport-actions .primary');const original=button.textContent;button.disabled=true;button.textContent='Generando PDF…';try{const canvas=await window.html2canvas(card,{scale:2,backgroundColor:'#06102a',useCORS:true});const image=canvas.toDataURL('image/png');const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'landscape',unit:'px',format:[canvas.width,canvas.height],hotfixes:['px_scaling']});pdf.addImage(image,'PNG',0,0,canvas.width,canvas.height);pdf.save(`pasaporte-universo-${(trip.name||'explorador').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.pdf`);}catch{window.print();}finally{button.disabled=false;button.textContent=original;}}
async function loginParticipant(event){
  event?.preventDefault();
  const name=document.querySelector("#name")?.value.trim()||"",email=document.querySelector("#email")?.value.trim().toLowerCase()||"";
  trip.name=name;participantEmail=email;
  if(name.length<2)return render("Escribe tu nombre completo.");
  if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return render("Escribe un correo electrónico válido.");
  const button=document.querySelector(".access-form .primary");if(button){button.disabled=true;button.textContent="Ingresando…";}
  try{
    const {data,error:err}=await db.rpc("universo_ingresar",{p_correo:email,p_nombre:name,p_legacy_client_id:clientId});
    if(err)throw err;const result=rpcPayload(data)||{};
    if(!result.token)throw new Error("Supabase no devolvió una sesión válida.");
    sessionToken=result.token;localStorage.setItem(SESSION_KEY,sessionToken);hydrate(result);
    view="map";startHeartbeat();render();
  }catch(err){render(`No pudimos ingresar: ${err.message||"intenta nuevamente."}`);}
}
function openFeedback(){const dialog=document.querySelector("#feedback-dialog");if(dialog&&!dialog.open)dialog.showModal();}
function closeFeedback(){document.querySelector("#feedback-dialog")?.close();}
async function saveFeedback(event){
  event.preventDefault();const form=event.currentTarget,rating=Number(new FormData(form).get("rating")),recommendation=document.querySelector("#feedback-recommendation")?.value.trim()||"";
  const status=document.querySelector("#feedback-status"),button=form.querySelector("button[type=submit]");button.disabled=true;status.textContent="Guardando tu evaluación…";
  try{const {data,error:err}=await db.rpc("universo_guardar_feedback",{p_token:sessionToken,p_calificacion:rating,p_recomendacion:recommendation});if(err)throw err;const saved=rpcPayload(data)||{};feedback={rating:Number(saved.calificacion)||rating,recommendation:saved.recomendacion??recommendation};status.textContent="Gracias. Tu evaluación quedó guardada.";setTimeout(closeFeedback,900);}catch(err){status.textContent=`No pudimos guardar: ${err.message||"intenta nuevamente."}`;}finally{button.disabled=false;}
}
async function logoutParticipant(){const token=sessionToken;sessionToken="";clearInterval(heartbeatTimer);localStorage.removeItem(SESSION_KEY);try{if(token)await db.rpc("universo_salir",{p_token:token});}catch{}trip={name:"",step:"lanzamiento",duels:{},satellites:[],mission:{}};participantEmail="";feedback={rating:0,recommendation:""};view="start";render();}
function showMap(){if(!sessionToken){view="start";return render();}view="map";render();}function showPassport(){if(!sessionToken)return;view="passport";render();}function goStep(step){localAnswer="";persist({step},"journey");}function answer(value){localAnswer=value;render();}function pickDuel(id){const picks={...trip.duels,[duelIndex]:id};if(duelIndex<duels.length-1){duelIndex++;persist({duels:picks});}else{const points=Object.keys(planets).reduce((a,k)=>(a[k]=0,a),{});Object.values(picks).forEach(x=>points[x]++);const rank=Object.keys(planets).sort((a,b)=>points[b]-points[a]);persist({duels:picks,mainPlanet:rank[0],explorePlanet:rank[1],step:"coordenadas"});}}function pickRole(role){persist({role,step:"satelites"});}function toggleSatellite(id){pendingSatellites=pendingSatellites.includes(id)?pendingSatellites.filter(x=>x!==id):[...pendingSatellites,id];render();}function saveSatellites(){persist({satellites:pendingSatellites,step:"observatorio"});}function saveObservatory(){persist({observatory:"CES · Esfuerzo del cliente",step:"mision"});}function saveMission(){const mission={accion:document.querySelector("#action").value.trim(),conQuien:document.querySelector("#with").value,aprendizaje:document.querySelector("#learning").value};if(!mission.accion||!mission.conQuien||!mission.aprendizaje)return render("Completa los tres componentes de tu misión.");persist({mission},"passport");}

function renderMap(message) { const index=steps.findIndex((s)=>s[0]===trip.step); const coordinates=[["22%","18%"],["47%","12%"],["77%","20%"],["83%","51%"],["70%","78%"],["23%","74%"],["50%","47%"]]; const hotspot=steps.map((s,i)=>`<button class="real-hotspot ${i<=index?"available":""}" style="left:${coordinates[i][0]};top:${coordinates[i][1]}" ${i>index?"disabled":""} onclick="goStep('${s[0]}')" aria-label="${s[1]}"><span class="hotspot-ring"></span><span class="hotspot-copy"><small>${i<index?"COMPLETADO":i===index?"SIGUIENTE SEÑAL":`MOMENTO ${i+1}`}</small><b>${s[1]}</b></span></button>`).join(""); app.innerHTML=`<main class="universo map-view">${nav()}<section class="map-head map-real-head"><div><p class="tag">Universo → mapa de navegación</p><p>Selecciona los cuerpos celestes para abrir cada territorio de la experiencia.</p></div><div class="counter"><b>${Math.max(0,index+1)}<small>de 7 momentos</small></b><span>Tu viaje</span></div></section><section class="real-orbital-map" style="background-image:linear-gradient(180deg,rgba(1,5,18,.05),rgba(1,5,18,.18)),url('assets/mapa-orbital-realista.png')" aria-label="Mapa orbital realista">${hotspot}</section>${error(message)}</main>`; }
load();
